require "maglev_record/snapshot/snapshotable"
require "maglev_record/snapshot/change"
require "maglev_record/snapshot/class_change"
require "maglev_record/snapshot/class_snapshot"
require "maglev_record/snapshot/snapshot"
require "maglev_record/snapshot/superclass_mismatch_change"
