# Java, because those are the 64bit boxes. We'll change it once Ruby
# boxes are 64bit, too
language: java
before_install:
  - "sudo apt-get install -qq rake"
before_script:
  - "./install.sh"
script:
  - "export MAGLEV_HOME=/home/travis/build/knub/maglevrecord/maglev"
  - "export PATH=$MAGLEV_HOME/bin:$PATH"
  - "gem uninstall -x -i /home/travis/.rvm/gems/ruby-1.9.3-p327@global bundler"
  - "maglev-gem install bundler"
  - "bundle install"
  - "gem install maglevrecord"
  - "bundle exec rake test"
notifications:
    email: false
