#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require 'fileutils'

#puts "bin in #{FileUtils.pwd}"
#puts "stone: #{Maglev::System.stone_name}"

$LOAD_PATH.unshift './maglevrecordgem'
$LOAD_PATH.unshift './maglevrecordgem/lib'

require 'maglev_record/raketasks'

require File.expand_path('../config/application', __FILE__)

Project1::Application.load_tasks
